export const ESCROW_ERROR_CODES = {
  AMOUNT_CANNOT_BE_ZERO: "ESCROW_AMOUNT_CANNOT_BE_ZERO",
  ESCROW_ALREADY_INITIALIZED: "ESCROW_ALREADY_INITIALIZED",
  ESCROW_NOT_FOUND: "ESCROW_NOT_FOUND",
  ONLY_RELEASE_SIGNER_CAN_RELEASE: "ESCROW_ONLY_RELEASE_SIGNER_CAN_RELEASE",
  ESCROW_BALANCE_NOT_ENOUGH_TO_SEND_EARNINGS:
    "ESCROW_BALANCE_NOT_ENOUGH_TO_SEND_EARNINGS",
  ONLY_PLATFORM_ADDRESS_CAN_EXECUTE: "ESCROW_ONLY_PLATFORM_ADDRESS_CAN_EXECUTE",
  ONLY_SERVICE_PROVIDER_CAN_CHANGE_MILESTONE_STATUS:
    "ESCROW_ONLY_SERVICE_PROVIDER_CAN_CHANGE_MILESTONE_STATUS",
  NO_MILESTONE_DEFINED: "ESCROW_NO_MILESTONE_DEFINED",
  INVALID_MILESTONE_INDEX: "ESCROW_INVALID_MILESTONE_INDEX",
  ONLY_APPROVER_CAN_CHANGE_MILESTONE_FLAG:
    "ESCROW_ONLY_APPROVER_CAN_CHANGE_MILESTONE_FLAG",
  ONLY_DISPUTE_RESOLVER_CAN_EXECUTE: "ESCROW_ONLY_DISPUTE_RESOLVER_CAN_EXECUTE",
  INSUFFICIENT_FUNDS_FOR_RESOLUTION: "ESCROW_INSUFFICIENT_FUNDS_FOR_RESOLUTION",
  OVERFLOW: "ESCROW_OVERFLOW",
  UNDERFLOW: "ESCROW_UNDERFLOW",
  DIVISION_ERROR: "ESCROW_DIVISION_ERROR",
  INSUFFICIENT_APPROVER_FUNDS_FOR_COMMISSIONS:
    "ESCROW_INSUFFICIENT_APPROVER_FUNDS_FOR_COMMISSIONS",
  INSUFFICIENT_SERVICE_PROVIDER_FUNDS_FOR_COMMISSIONS:
    "ESCROW_INSUFFICIENT_SERVICE_PROVIDER_FUNDS_FOR_COMMISSIONS",
  MILESTONE_APPROVED_CANT_CHANGE_ESCROW_PROPERTIES:
    "ESCROW_MILESTONE_APPROVED_CANT_CHANGE_PROPERTIES",
  ESCROW_HAS_FUNDS: "ESCROW_HAS_FUNDS",
  TOO_MANY_ESCROWS_REQUESTED: "ESCROW_TOO_MANY_ESCROWS_REQUESTED",
  UNAUTHORIZED_TO_CHANGE_DISPUTE_FLAG:
    "ESCROW_UNAUTHORIZED_TO_CHANGE_DISPUTE_FLAG",
  TOO_MANY_MILESTONES: "ESCROW_TOO_MANY_MILESTONES",
  EMPTY_MILESTONE_STATUS: "ESCROW_EMPTY_MILESTONE_STATUS",
  PLATFORM_FEE_TOO_HIGH: "ESCROW_PLATFORM_FEE_TOO_HIGH",
  FLAGS_MUST_BE_FALSE: "ESCROW_FLAGS_MUST_BE_FALSE",
  ESCROW_PROPERTIES_MISMATCH: "ESCROW_PROPERTIES_MISMATCH",
  APPROVER_OR_RECEIVER_FUNDS_LESS_THAN_ZERO:
    "ESCROW_APPROVER_OR_RECEIVER_FUNDS_LESS_THAN_ZERO",
  INCOMPATIBLE_ESCROW_WASM_HASH: "ESCROW_INCOMPATIBLE_WASM_HASH",
  PLATFORM_ADDRESS_CANNOT_BE_CHANGED:
    "ESCROW_PLATFORM_ADDRESS_CANNOT_BE_CHANGED",
  AMOUNTS_TO_TRANSFER_SHOULD_BE_POSITIVE:
    "ESCROW_AMOUNTS_TO_TRANSFER_SHOULD_BE_POSITIVE",
  TOTAL_AMOUNT_CANNOT_BE_ZERO: "ESCROW_TOTAL_AMOUNT_CANNOT_BE_ZERO",
  INSUFFICIENT_FUNDS_FOR_FUNDING: "ESCROW_INSUFFICIENT_FUNDS_FOR_FUNDING",
  MILESTONE_TO_APPROVE_DOES_NOT_EXIST:
    "ESCROW_MILESTONE_TO_APPROVE_DOES_NOT_EXIST",
  ESCROW_NOT_FULLY_PROCESSED: "ESCROW_NOT_FULLY_PROCESSED",
  TOO_MANY_DISTRIBUTIONS: "ESCROW_TOO_MANY_DISTRIBUTIONS",
  MILESTONE_TO_UPDATE_DOES_NOT_EXIST:
    "ESCROW_MILESTONE_TO_UPDATE_DOES_NOT_EXIST",
  MILESTONE_HAS_ALREADY_BEEN_APPROVED:
    "ESCROW_MILESTONE_HAS_ALREADY_BEEN_APPROVED",
  ESCROW_BALANCE_MUST_BE_ZERO_ON_INITIALIZATION:
    "ESCROW_BALANCE_MUST_BE_ZERO_ON_INITIALIZATION",
  ONLY_ADMIN_CAN_EXECUTE: "ESCROW_ONLY_ADMIN_CAN_EXECUTE",
  ADMIN_ADDRESS_CANNOT_BE_CHANGED: "ESCROW_ADMIN_ADDRESS_CANNOT_BE_CHANGED",
  ADMIN_ADDRESS_OVERLAPS_WITH_OTHER_ROLE:
    "ESCROW_ADMIN_ADDRESS_OVERLAPS_WITH_OTHER_ROLE",
  DISPUTE_RESOLVER_OVERLAPS_WITH_OTHER_ROLE:
    "ESCROW_DISPUTE_RESOLVER_OVERLAPS_WITH_OTHER_ROLE",
  APPROVERS_LIST_EMPTY: "ESCROW_APPROVERS_LIST_EMPTY",
  SERVICE_PROVIDERS_LIST_EMPTY: "ESCROW_SERVICE_PROVIDERS_LIST_EMPTY",
  RELEASE_SIGNERS_LIST_EMPTY: "ESCROW_RELEASE_SIGNERS_LIST_EMPTY",
  DISPUTE_RESOLVERS_LIST_EMPTY: "ESCROW_DISPUTE_RESOLVERS_LIST_EMPTY",
  ROLE_LIMIT_EXCEEDED: "ESCROW_ROLE_LIMIT_EXCEEDED",
  DUPLICATE_ADDRESS_IN_ROLE: "ESCROW_DUPLICATE_ADDRESS_IN_ROLE",
  TARGET_CANNOT_BE_ZERO: "ESCROW_TARGET_CANNOT_BE_ZERO",
  TARGET_EXCEEDS_APPROVERS: "ESCROW_TARGET_EXCEEDS_APPROVERS",
  MILESTONE_UPDATE_NOT_ALLOWED_WITH_FUNDS:
    "ESCROW_MILESTONE_UPDATE_NOT_ALLOWED_WITH_FUNDS",
  STRING_TOO_LONG: "ESCROW_STRING_TOO_LONG",
  REENTRANCY: "ESCROW_REENTRANCY",
  APPROVER_ALREADY_APPROVED_MILESTONE:
    "ESCROW_APPROVER_ALREADY_APPROVED_MILESTONE",
  UNAUTHORIZED_APPROVER: "ESCROW_UNAUTHORIZED_APPROVER",
  BATCH_MILESTONE_UPDATE_EMPTY: "ESCROW_BATCH_MILESTONE_UPDATE_EMPTY",
  BATCH_MILESTONE_APPROVE_EMPTY: "ESCROW_BATCH_MILESTONE_APPROVE_EMPTY",
  DUPLICATE_MILESTONE_INDEX: "ESCROW_DUPLICATE_MILESTONE_INDEX",
  BATCH_TOO_LARGE: "ESCROW_BATCH_TOO_LARGE",
  RELEASE_MILESTONES_EMPTY: "ESCROW_RELEASE_MILESTONES_EMPTY",
  BATCH_MILESTONE_DISPUTE_EMPTY: "ESCROW_BATCH_MILESTONE_DISPUTE_EMPTY",
  MILESTONE_ALREADY_DISPUTED: "ESCROW_MILESTONE_ALREADY_DISPUTED",
  SIGNER_MUST_BE_APPROVER_AND_RELEASE_SIGNER:
    "ESCROW_SIGNER_MUST_BE_APPROVER_AND_RELEASE_SIGNER",
  ESCROW_NOT_COMPLETED: "ESCROW_NOT_COMPLETED",
  ESCROW_ALREADY_IN_DISPUTE: "ESCROW_ALREADY_IN_DISPUTE",
  ESCROW_NOT_IN_DISPUTE: "ESCROW_NOT_IN_DISPUTE",
  ESCROW_OPENED_FOR_DISPUTE_RESOLUTION: "ESCROW_OPENED_FOR_DISPUTE_RESOLUTION",
  ESCROW_ALREADY_RESOLVED: "ESCROW_ALREADY_RESOLVED",
  RECEIVER_AND_APPROVER_FUNDS_NOT_EQUAL:
    "ESCROW_RECEIVER_AND_APPROVER_FUNDS_NOT_EQUAL",
  ESCROW_ALREADY_RELEASED: "ESCROW_ALREADY_RELEASED",
  DISTRIBUTIONS_MUST_EQUAL_ESCROW_BALANCE:
    "ESCROW_DISTRIBUTIONS_MUST_EQUAL_BALANCE",
  DISPUTE_RESOLVER_CANNOT_DISPUTE_ESCROW:
    "ESCROW_DISPUTE_RESOLVER_CANNOT_DISPUTE",
  ESCROW_NOT_FUNDED: "ESCROW_NOT_FUNDED",
  MILESTONE_NOT_COMPLETED: "ESCROW_MILESTONE_NOT_COMPLETED",
  MILESTONE_ALREADY_IN_DISPUTE: "ESCROW_MILESTONE_ALREADY_IN_DISPUTE",
  MILESTONE_NOT_IN_DISPUTE: "ESCROW_MILESTONE_NOT_IN_DISPUTE",
  MILESTONE_OPENED_FOR_DISPUTE_RESOLUTION:
    "ESCROW_MILESTONE_OPENED_FOR_DISPUTE_RESOLUTION",
  MILESTONE_ALREADY_RESOLVED: "ESCROW_MILESTONE_ALREADY_RESOLVED",
  CANT_RELEASE_A_MILESTONE_IN_DISPUTE:
    "ESCROW_CANT_RELEASE_A_MILESTONE_IN_DISPUTE",
  MILESTONE_ALREADY_RELEASED: "ESCROW_MILESTONE_ALREADY_RELEASED",
  MILESTONE_NOT_FOUND: "ESCROW_MILESTONE_NOT_FOUND",
  TOTAL_DISPUTE_FUNDS_MUST_NOT_EXCEED_THE_MILESTONE_AMOUNT:
    "ESCROW_TOTAL_DISPUTE_FUNDS_MUST_NOT_EXCEED_MILESTONE_AMOUNT",
  INSUFFICIENT_FUNDS_FOR_REFUND: "ESCROW_INSUFFICIENT_FUNDS_FOR_REFUND",
  INSUFFICIENT_ESCROW_FUNDS_TO_MAKE_THE_REFUND:
    "ESCROW_INSUFFICIENT_ESCROW_FUNDS_TO_MAKE_REFUND",
  DISPUTE_RESOLVER_CANNOT_DISPUTE_THE_MILESTONE:
    "ESCROW_DISPUTE_RESOLVER_CANNOT_DISPUTE_MILESTONE",
} as const;

export type EscrowErrorCode =
  (typeof ESCROW_ERROR_CODES)[keyof typeof ESCROW_ERROR_CODES];

const ESCROW_ERROR_CODE_SET = new Set<string>(
  Object.values(ESCROW_ERROR_CODES),
);

export function isEscrowErrorCode(code: string): code is EscrowErrorCode {
  return ESCROW_ERROR_CODE_SET.has(code);
}
